# Generated by Django 4.2.6 on 2023-10-20 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_nombre_bebidas_nombre_bebida'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaDeBebidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la categoría', max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de la categoría', null=True)),
                ('bebida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.bebidas')),
            ],
        ),
    ]
