# Generated by Django 4.2.6 on 2023-10-20 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_categoriadebebidas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriadebebidas',
            name='bebida',
        ),
        migrations.AddField(
            model_name='bebidas',
            name='category_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.categoriadebebidas'),
        ),
        migrations.AlterField(
            model_name='bebidas',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción de la categoría', null=True),
        ),
    ]
