# Generated by Django 4.2.6 on 2023-10-20 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_categoriadebebidas_bebida_bebidas_category_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bebidas',
            name='category_id',
        ),
        migrations.AddField(
            model_name='bebidas',
            name='categoria',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='myapp.categoriadebebidas'),
        ),
    ]
