# Generated by Django 4.2.6 on 2023-10-20 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_bebidas_category_id_bebidas_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bebidas',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.categoriadebebidas'),
        ),
    ]
